name: Repro
on:
  push:
    branches: [master]
jobs:
  j:
    name: Reproduce bug
    runs-on: windows-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5
      - name: VC Vars
        uses: ilammy/msvc-dev-cmd@v1
      - name: Configure
        run: cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=Debug
      - name: Build
        run: cmake --build build
      - name: No align
        run: cmake --build build --target run-no-align-no-repro
      - name: No heap alloc
        run: cmake --build build --target run-no-heap-alloc-no-repro
      - name: No deduce
        run: cmake --build build --target run-no-deduce-no-repro
      - name: Repro
        run: cmake --build build --target run-repro
